const CACHE_NAME = 'contour-app-pwa-v25';
const APP_ASSETS = [
  './',
  './index.html',
  './gate.js',
  './manifest.json',
  './sefaria-bdb.js',
  './greek-lexicon.js',
  './css/app.css',
  './js/data/books.js',
  './js/data/wlc-text.js',
  './js/app/core.js',
  './js/app/undo.js',
  './js/app/layout.js',
  './js/app/file-menu.js',
  './js/app/arcs.js',
  './js/app/keyboard.js',
  './js/app/annotations.js',
  './js/app/theme.js',
  './js/app/inspector.js',
  './js/app/inspector-morph.js',
  './js/app/ui-init.js',
  './icons/icon-192.png',
  './icons/icon-512.png'
];
