/* Parallel passages (desktop): dual panes, verse alignment, cross-pane arcs */
const PARALLEL_MIN_WIDTH=1024;
let stateBundle={parallelEnabled:false,activePane:0,crossArcs:[],generatedRefsByPane:[[],[]],panes:[null,null]};
function freshPaneState(){return {ref:'',verses:[],selected:null,columns:[],language:'hebrew',legend:[],inclusios:[],comments:[],activeCommentId:null,arcs:[],activeArcId:null};}
function ensureStateBundle(){if(!stateBundle.panes[0])stateBundle.panes[0]=freshPaneState();if(!stateBundle.panes[1])stateBundle.panes[1]=freshPaneState();if(!stateBundle.generatedRefsByPane[0])stateBundle.generatedRefsByPane[0]=[];if(!stateBundle.generatedRefsByPane[1])stateBundle.generatedRefsByPane[1]=[];}
function bindActivePane(idx){ensureStateBundle();const i=idx===1?1:0;stateBundle.generatedRefsByPane[stateBundle.activePane]=generatedRefs.slice();stateBundle.activePane=i;state=stateBundle.panes[i];generatedRefs=stateBundle.generatedRefsByPane[i]||[];syncGeneratorFieldsFromActivePane();updateParallelModeUI();}
function syncGeneratorFieldsFromActivePane(){const refBox=document.getElementById('refBox');const pasteBox=document.getElementById('pasteBox');const textSource=document.getElementById('textSource');if(refBox)refBox.value=state.ref||'';if(pasteBox&&state.verses&&state.verses.length){pasteBox.value=state.verses.map(v=>v.clauses.flatMap(c=>c.words).filter(w=>!w.deleted).map(w=>w.text).join(' ')).join('\n');pasteBox.dir=state.language==='greek'?'ltr':'rtl';pasteBox.classList.remove('heb','greek');pasteBox.classList.add(state.language==='greek'?'greek':'heb');}if(textSource){const lang=state.language==='greek'?'greek':(state.language==='hebrew-bhsa'?'hebrew-bhsa':'hebrew');textSource.value=lang;if(typeof setupBooks==='function')setupBooks();}}
function syncStateBundle(){ensureStateBundle();stateBundle.generatedRefsByPane[stateBundle.activePane]=generatedRefs.slice();stateBundle.panes[stateBundle.activePane]=state;}
function isParallelActive(){return !!stateBundle.parallelEnabled&&window.matchMedia(`(min-width:${PARALLEL_MIN_WIDTH}px)`).matches;}
function paneLabel(idx){return idx===0?'Left passage':'Right passage';}
function normalizeProjectState(st){ensureStateBundle();if(st&&Array.isArray(st.panes)&&st.panes.length>=2){return {parallelEnabled:!!st.parallelEnabled,activePane:st.activePane===1?1:0,crossArcs:Array.isArray(st.crossArcs)?st.crossArcs:[],panes:[Object.assign(freshPaneState(),st.panes[0]||{}),Object.assign(freshPaneState(),st.panes[1]||{})]};}const legacy=Object.assign(freshPaneState(),st||{});return {parallelEnabled:false,activePane:0,crossArcs:[],panes:[legacy,freshPaneState()]};}
function locOKInPane(l,pane){const p=pane!=null?pane:stateBundle.activePane;const st=stateBundle.panes[p];return !!(l&&st&&st.verses[l.v]&&st.verses[l.v].clauses[l.c]&&st.verses[l.v].clauses[l.c].words[l.w]);}
function locFromWordElWithPane(el){if(!el)return null;const loc={v:+el.dataset.v,c:+el.dataset.c,w:+el.dataset.w};if(el.dataset.pane!=null)loc.pane=+el.dataset.pane;return loc;}
function cloneLocWithPane(l){if(!l)return null;const o={v:+l.v,c:+l.c,w:+l.w};if(l.pane!=null)o.pane=+l.pane;return o;}
function computeVersePairs(){const left=stateBundle.panes[0].verses||[];const right=stateBundle.panes[1].verses||[];const n=Math.max(left.length,right.length,0);const pairs=[];for(let i=0;i<n;i++)pairs.push({leftVi:i<left.length?i:null,rightVi:i<right.length?i:null});return pairs;}
function paneLanguage(pane){const st=stateBundle.panes[pane];return st&&st.language?st.language:'hebrew';}
function renderVerseBlock(pane,vi,paneState,layout,activeKey){if(vi==null||!paneState.verses[vi])return '<div class="parallel-empty-verse muted small">—</div>';const v=paneState.verses[vi];let html=`<div class="muted parallel-verse-ref" dir="ltr">${esc(v.ref)}</div>`;v.clauses.forEach((c,ci)=>{const sel=paneState.selected&&paneState.selected.v===vi&&paneState.selected.c===ci;const marginStyle=layout.indentSide==='left'?`margin-left:${c.indent*36}px`:`margin-right:${c.indent*36}px`;html+=`<div class="clause ${sel?'selected':''}" data-pane="${pane}" data-v="${vi}" data-c="${ci}" dir="${layout.dir}" style="${marginStyle};direction:${layout.dir};text-align:${layout.textAlign};font-family:${layout.fontFamily}">`;c.words.forEach((w,wi)=>{const l={v:vi,c:ci,w:wi,pane};const ids=commentIdsForLocInPane(l,pane);const commentClass=ids.length?'comment-anchored':'';const activeCommentClass=(paneState.activeCommentId&&ids.includes(paneState.activeCommentId))?'comment-active':'';const wsel=paneState.selected&&paneState.selected.v===vi&&paneState.selected.c===ci&&paneState.selected.w===wi;const same=activeKey&&normalizeHebrewWord(w.text)===activeKey&&!wsel;html+=`<span class="word ${wsel?'selected':''} ${same?'sameword':''} ${commentClass} ${activeCommentClass} ${w.deleted?'deleted':''} ${w.specials.includes('predicate')?'pred':''} ${w.specials.includes('subject')?'subj':''} ${wordFormatClasses(w,l)}" data-pane="${pane}" data-v="${vi}" data-c="${ci}" data-w="${wi}" style="${wordInlineStyle(w)}">${esc(w.text)}</span>${commentMarkersForLocInPane(l,pane)} `;});html+='</div>';});return html;}
function locRankInPane(l,pane){const st=stateBundle.panes[pane];if(!st||!locOKInPane(l,pane))return-1;let n=0;for(let vi=0;vi<st.verses.length;vi++){for(let ci=0;ci<st.verses[vi].clauses.length;ci++){if(vi===l.v&&ci===l.c)return n+l.w;n+=st.verses[vi].clauses[ci].words.length;}}return-1;}
function locInRangeInPane(l,start,end,pane){if(!locOKInPane(l,pane)||!locOKInPane(start,pane)||!locOKInPane(end,pane))return false;const r=locRankInPane(l,pane),a=locRankInPane(start,pane),b=locRankInPane(end,pane);return r>=Math.min(a,b)&&r<=Math.max(a,b);}
function commentIdsForLocInPane(l,pane){const st=stateBundle.panes[pane];if(!st||!Array.isArray(st.comments))return[];return st.comments.filter(cm=>locOKInPane(cm.start,pane)&&locOKInPane(cm.end,pane)&&locInRangeInPane(l,cm.start,cm.end,pane)).map(cm=>cm.id);}
function commentMarkersForLocInPane(l,pane){const st=stateBundle.panes[pane];if(!st||!Array.isArray(st.comments))return'';return st.comments.map((cm,idx)=>locOKInPane(cm.start,pane)&&locEqual(l,cm.start)?`<sup class="comment-marker" data-comment-id="${esc(cm.id)}">${idx+1}</sup>`:'').join('');}
function sameLocInPane(a,b,pane){return locOKInPane(a,pane)&&locOKInPane(b,pane)&&a.v===b.v&&a.c===b.c&&a.w===b.w;}
function attachParallelWordHandlers(root){root.querySelectorAll('.word').forEach(el=>{el.onclick=(ev)=>{const pane=+el.dataset.pane;bindActivePane(pane);const clicked={v:+el.dataset.v,c:+el.dataset.c,w:+el.dataset.w};if(ev.shiftKey&&locOK(state.selected)){applyBracketRange(state.selected,clicked);return;}state.selected=clicked;renderParallelEditors();};});root.querySelectorAll('.clause').forEach(el=>{el.onclick=(ev)=>{if(ev.target.classList.contains('word'))return;bindActivePane(+el.dataset.pane);state.selected={v:+el.dataset.v,c:+el.dataset.c,w:0};renderParallelEditors();};});}
function equalizeParallelRowHeights(){document.querySelectorAll('.parallel-verse-row').forEach(row=>{const cells=row.querySelectorAll('.parallel-verse-cell');let maxH=0;cells.forEach(c=>{c.style.minHeight='';maxH=Math.max(maxH,c.offsetHeight);});cells.forEach(c=>{c.style.minHeight=maxH+'px';});});}
function renderParallelEditors(){ensureStateBundle();const wrap=document.getElementById('parallelCompareWrap');const single=document.getElementById('singleEditorSection');const rowsEl=document.getElementById('parallelVerseRows');if(!wrap||!rowsEl)return;if(!isParallelActive()){wrap.classList.add('hidden');if(single)single.classList.remove('hidden');return;}wrap.classList.remove('hidden');if(single)single.classList.add('hidden');const pairs=computeVersePairs();let html='';[0,1].forEach(pane=>{const head=document.getElementById('parallelPaneHead'+pane);if(head){const st=stateBundle.panes[pane];head.textContent=st.ref||paneLabel(pane);head.classList.toggle('parallel-pane-active',stateBundle.activePane===pane);}});pairs.forEach((pair,ri)=>{html+=`<div class="parallel-verse-row" data-row="${ri}">`;[0,1].forEach(pane=>{const vi=pane===0?pair.leftVi:pair.rightVi;const paneState=stateBundle.panes[pane];const layout=getLanguageLayout(paneState.language);const activeKey=paneState.selected&&locOKInPane(paneState.selected,pane)?normalizeHebrewWord(paneState.verses[paneState.selected.v].clauses[paneState.selected.c].words[paneState.selected.w].text):'';html+=`<div class="parallel-verse-cell ${stateBundle.activePane===pane?'pane-active':''}" data-pane="${pane}" data-row="${ri}"><div class="parallel-pane-arc-wrap" data-pane="${pane}"><svg class="paneArcSvg" data-pane="${pane}" aria-hidden="true"></svg><div class="parallel-verse-body">${renderVerseBlock(pane,vi,paneState,layout,activeKey)}</div></div></div>`;});html+='</div>';});if(!pairs.length)html='<div class="editor-empty-state" dir="ltr"><p class="editor-empty-title">Load a passage into each pane</p><p class="muted">Use <strong>Generate text</strong> or <strong>Paste text</strong> — the active pane is highlighted below.</p></div>';rowsEl.innerHTML=html;attachParallelWordHandlers(rowsEl);requestAnimationFrame(()=>{equalizeParallelRowHeights();renderParallelArcOverlays();renderCrossArcOverlay();updateParallelModeUI();});}
function renderParallelArcOverlays(){[0,1].forEach(pane=>{const paneState=stateBundle.panes[pane];ensureArcsInPane(pane);const svg=document.querySelector(`.paneArcSvg[data-pane="${pane}"]`);const wrap=document.querySelector(`.parallel-pane-arc-wrap[data-pane="${pane}"]`);if(!svg||!wrap)return;svg.innerHTML='';const wr=wrap.getBoundingClientRect();svg.setAttribute('viewBox',`0 0 ${Math.max(1,wr.width)} ${Math.max(1,wr.height)}`);svg.setAttribute('width',wr.width);svg.setAttribute('height',wr.height);document.querySelectorAll(`.word[data-pane="${pane}"].arc-anchor`).forEach(w=>w.classList.remove('arc-anchor'));paneState.arcs.forEach(arc=>{const a=wordElForLoc(arc.start,pane);const b=wordElForLoc(arc.end,pane);if(!a||!b)return;a.classList.add('arc-anchor');b.classList.add('arc-anchor');const geo=arcGeometryForLocsInPane(arc.start,arc.end,pane,wr);if(!geo)return;const color=arc.color||'#0b61d8';drawArcPath(svg,geo,color);drawArcLabel(svg,geo,arc,color);});});}
function ensureArcsInPane(pane){const st=stateBundle.panes[pane];if(!Array.isArray(st.arcs))st.arcs=[];}
function arcGeometryForLocsInPane(start,end,pane,wrapRect){const a=wordElForLoc(start,pane);const b=wordElForLoc(end,pane);if(!a||!b)return null;const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect();const isGreek=paneLanguage(pane)==='greek';const y1=ar.top+ar.height/2-wrapRect.top,y2=br.top+br.height/2-wrapRect.top;const anchor1=isGreek?ar.left-wrapRect.left:ar.right-wrapRect.left;const anchor2=isGreek?br.left-wrapRect.left:br.right-wrapRect.left;const textEdge=isGreek?Math.min(ar.left,br.left)-wrapRect.left:Math.max(ar.right,br.right)-wrapRect.left;const sideX=isGreek?Math.max(8,textEdge-46):Math.min(wrapRect.width-8,textEdge+46);return {isGreek,y1,y2,anchor1,anchor2,sideX,mid:(y1+y2)/2};}
function ensureCrossArcs(){if(!Array.isArray(stateBundle.crossArcs))stateBundle.crossArcs=[];}
function renderCrossArcOverlay(){ensureCrossArcs();const layer=document.getElementById('crossArcLayer');const svg=document.getElementById('crossArcSvg');if(!layer||!svg)return;svg.innerHTML='';const lr=layer.getBoundingClientRect();svg.setAttribute('viewBox',`0 0 ${Math.max(1,lr.width)} ${Math.max(1,lr.height)}`);svg.setAttribute('width',lr.width);svg.setAttribute('height',lr.height);stateBundle.crossArcs.forEach(arc=>{const sp=arc.start.pane!=null?+arc.start.pane:0;const ep=arc.end.pane!=null?+arc.end.pane:1;const a=wordElForLoc({v:arc.start.v,c:arc.start.c,w:arc.start.w},sp);const b=wordElForLoc({v:arc.end.v,c:arc.end.c,w:arc.end.w},ep);if(!a||!b)return;const geo=crossArcGeometry(a,b,lr);if(!geo)return;const color=arc.color||'#7b2cbf';drawArcPath(svg,geo,color);drawArcLabel(svg,geo,arc,color);});}
function crossArcGeometry(aEl,bEl,layerRect){const ar=aEl.getBoundingClientRect(),br=bEl.getBoundingClientRect();const x1=ar.left+ar.width/2-layerRect.left;const x2=br.left+br.width/2-layerRect.left;const y1=ar.top+ar.height/2-layerRect.top;const y2=br.top+br.height/2-layerRect.top;const sideX=(x1+x2)/2;const mid=Math.min(y1,y2)-36;return {isGreek:true,y1,y2,anchor1:x1,anchor2:x2,sideX,mid};}
function addCrossArcFromLocs(start,end){ensureCrossArcs();if(!start||!end||start.pane==null||end.pane==null||start.pane===end.pane)return null;if(!locOKInPane(start,start.pane)||!locOKInPane(end,end.pane))return null;if(start.pane===end.pane&&sameLocInPane(start,end,start.pane))return null;const arc={id:nextCrossArcId(),start:cloneLocWithPane(start),end:cloneLocWithPane(end),color:arcColorValue(),label:arcLabelValue()};stateBundle.crossArcs.push(arc);autoSaveProject();return arc;}
let crossArcIdSeq=1;function nextCrossArcId(){return 'crossarc-'+(crossArcIdSeq++);}
function addArcFromLocsParallel(start,end){if(!start||!end)return null;const sp=start.pane!=null?+start.pane:stateBundle.activePane;const ep=end.pane!=null?+end.pane:stateBundle.activePane;if(sp!==ep)return addCrossArcFromLocs(Object.assign({pane:sp},start),Object.assign({pane:ep},end));bindActivePane(sp);return addArcFromLocs({v:start.v,c:start.c,w:start.w},{v:end.v,c:end.c,w:end.w});}
function deleteSelectedArcParallel(id){ensureCrossArcs();const target=id||state.activeArcId;if(!target){alert('Select an arc in the Arc connectors list first.');return;}if(String(target).startsWith('crossarc-')){stateBundle.crossArcs=stateBundle.crossArcs.filter(a=>a.id!==target);}else{ensureArcs();state.arcs=state.arcs.filter(a=>a.id!==target);}if(state.activeArcId===target)state.activeArcId=null;autoSaveProject();render();}
function resetParallelProjectState(){stateBundle={parallelEnabled:false,activePane:0,crossArcs:[],generatedRefsByPane:[[],[]],panes:[freshProjectState(),freshProjectState()]};state=stateBundle.panes[0];generatedRefs=[];const toggle=document.getElementById('parallelModeToggle');if(toggle)toggle.checked=false;}
function renderArcManagerParallel(){const mgr=document.getElementById('arcManager');if(!mgr)return;if(!isParallelActive()){renderArcManager();return;}ensureCrossArcs();let html='<div class="small"><strong>Cross-pane arcs</strong></div>';if(!stateBundle.crossArcs.length)html+='<p class="muted small">Draw from a word in one passage to a word in the other.</p>';stateBundle.crossArcs.forEach(arc=>{html+=`<div class="arc-item ${state.activeArcId===arc.id?'active':''}" data-arc-id="${esc(arc.id)}"><span>${esc(arcLabelText(arc))}</span> <span class="muted">${esc(paneLabel(arc.start.pane))} → ${esc(paneLabel(arc.end.pane))}</span></div>`;});[0,1].forEach(pane=>{const st=stateBundle.panes[pane];if(!st.arcs||!st.arcs.length)return;html+=`<div class="small" style="margin-top:8px"><strong>${esc(paneLabel(pane))} arcs</strong></div>`;st.arcs.forEach(arc=>{html+=`<div class="arc-item ${state.activeArcId===arc.id?'active':''}" data-arc-id="${esc(arc.id)}" data-pane="${pane}"><span>${esc(arcLabelText(arc))}</span></div>`;});});mgr.innerHTML=html;mgr.querySelectorAll('.arc-item').forEach(el=>{el.onclick=()=>{if(el.dataset.pane)bindActivePane(+el.dataset.pane);state.activeArcId=el.dataset.arcId;render();};});}
function buildTableHtmlForPane(paneState,pane){const savedState=state;const savedRefs=generatedRefs;state=paneState;generatedRefs=stateBundle.generatedRefsByPane[pane]||[];const rows=clauseRows();const textHeader=(paneState.language==='greek'?'Greek Text':'Hebrew Text');const textClass=(paneState.language==='greek'?'greek':'heb');const ltr=' class="ann-ltr" dir="ltr"';let html=`<table class="annTable parallel-ann-table" data-pane="${pane}" dir="ltr"><thead><tr><th class="${textClass}">${textHeader}</th><th${ltr}>Translation</th><th${ltr}>Gloss</th><th${ltr}>Parsing</th><th${ltr}>Notes</th>`;paneState.columns.forEach(col=>html+=`<th class="ann-ltr" dir="ltr">${esc(col)}</th>`);html+='</tr></thead><tbody>';rows.forEach(r=>{html+=`<tr data-pane="${pane}" data-v="${r.vi}" data-c="${r.ci}"><td class="${textClass}">${esc(r.hebrew)}</td><td class="ann-ltr" dir="ltr" contenteditable data-col="Translation">${esc(r.ann['Translation']||'')}</td><td class="ann-ltr" dir="ltr">${esc(r.translation)}</td><td class="ann-ltr" dir="ltr" contenteditable data-col="Parsing">${esc(r.ann['Parsing']||'')}</td><td class="ann-ltr" dir="ltr">${esc(r.notes)}</td>`;paneState.columns.forEach(col=>html+=`<td class="ann-ltr" dir="ltr" contenteditable data-col="${esc(col)}">${esc(r.ann[col]||'')}</td>`);html+='</tr>';});html+='</tbody></table>';state=savedState;generatedRefs=savedRefs;return html;}
function renderDualTables(){const tableWrap=document.getElementById('tableWrap');if(!tableWrap)return;let html='';[0,1].forEach(pane=>{const paneState=stateBundle.panes[pane];html+=`<div class="parallel-table-block"><h3 class="parallel-table-title">${esc(paneState.ref||paneLabel(pane))}</h3>${buildTableHtmlForPane(paneState,pane)}</div>`;});tableWrap.innerHTML=html;tableWrap.dir='ltr';document.querySelectorAll('.parallel-ann-table td[contenteditable]').forEach(td=>{td.oninput=()=>{const tr=td.closest('tr');const pane=+tr.dataset.pane;const st=stateBundle.panes[pane];const c=st.verses[+tr.dataset.v].clauses[+tr.dataset.c];c.ann=c.ann||{};c.ann[td.dataset.col]=td.innerText;if(autosaveReady)autoSaveProject();};});}
function pickExportScope(){return new Promise(resolve=>{if(!isParallelActive()){resolve({panes:[stateBundle.activePane],mode:'single'});return;}const left=stateBundle.panes[0].verses.length;const right=stateBundle.panes[1].verses.length;if(!left&&!right){resolve(null);return;}const modal=document.getElementById('exportScopeModal');if(!modal){resolve({panes:left&&right?[0,1]:left?[0]:[1],mode:'both'});return;}const done=(panes,mode)=>{modal.classList.remove('show');resolve({panes,mode});};document.getElementById('exportScopeLeft').onclick=()=>done([0],'left');document.getElementById('exportScopeRight').onclick=()=>done([1],'right');document.getElementById('exportScopeBoth').onclick=()=>done([0,1],'both');document.getElementById('exportScopeCancel').onclick=()=>{modal.classList.remove('show');resolve(null);};modal.classList.add('show');});}
function withPaneExport(pane,fn){const savedPane=stateBundle.activePane;bindActivePane(pane);try{return fn();}finally{syncStateBundle();bindActivePane(savedPane);}}
function exportContourDocxParallel(){if(!stateBundle.panes[0].verses.length&&!stateBundle.panes[1].verses.length){alert('Create or generate text first.');return;}pickExportScope().then(scope=>{if(!scope)return;const panes=scope.panes;const base=suggestedExportBase('contour-editor');if(panes.length===1){withPaneExport(panes[0],()=>exportContourDocx());return;}let body='';panes.forEach((p,i)=>{if(i)body+='<w:p><w:r><w:br w:type="page"/></w:r></w:p>';body+=extractDocxBody(contourDocxXmlForPane(p));});const fname=askExportFilename(base,'docx');if(!fname)return;downloadDocxZip(docxZipFiles(wrapDocxBody(body)),fname);});}
function contourDocxXmlForPane(pane){return withPaneExport(pane,()=>contourDocxXml());}
function docxXmlForPane(pane){return withPaneExport(pane,()=>docxXml());}
function extractDocxBody(xml){const m=String(xml||'').match(/<w:body>([\s\S]*)<\/w:body>/);return m?m[1]:'';}
function wrapDocxBody(body){return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'+body+'<w:sectPr><w:pgSz w:w="12240" w:h="15840"/></w:sectPr></w:body></w:document>';}
function docxZipFiles(documentXml){return [{name:'[Content_Types].xml',data:'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'},{name:'_rels/.rels',data:'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'},{name:'word/document.xml',data:documentXml}];}
function downloadDocxZip(files,fname){const a=document.createElement('a');a.href=URL.createObjectURL(makeZip(files));a.download=fname;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function exportContourPdfParallel(){if(!stateBundle.panes[0].verses.length&&!stateBundle.panes[1].verses.length){alert('Create or generate text first.');return;}pickExportScope().then(scope=>{if(!scope)return;if(scope.panes.length===1){withPaneExport(scope.panes[0],()=>exportContourPdf());return;}alert('For PDF, export each passage separately (Left / Right) or use Word export for both passages.');});}
function exportTableDocxParallel(){const has=[0,1].some(p=>stateBundle.panes[p].verses.length);if(!has){alert('Create or generate text first.');return;}pickExportScope().then(scope=>{if(!scope)return;const panes=scope.panes;const base=suggestedExportBase('contour-table');if(panes.length===1){withPaneExport(panes[0],()=>{const fname=askExportFilename(base,'docx');if(!fname)return;downloadDocxZip(docxZipFiles(wrapDocxBody(extractDocxBody(docxXml()))),fname);});return;}let body='';panes.forEach((p,i)=>{if(i)body+='<w:p><w:r><w:br w:type="page"/></w:r></w:p>';body+=extractDocxBody(docxXmlForPane(p));});const fname=askExportFilename(base,'docx');if(!fname)return;downloadDocxZip(docxZipFiles(wrapDocxBody(body)),fname);});}
function exportTablePdfParallel(){const has=[0,1].some(p=>stateBundle.panes[p].verses.length);if(!has){alert('Create or generate text first.');return;}pickExportScope().then(scope=>{if(!scope)return;if(scope.panes.length===1){withPaneExport(scope.panes[0],()=>exportTablePdf());return;}alert('For PDF, export each passage separately (Left / Right) or use Word export for both passages.');});}
function updateParallelModeUI(){const ind=document.getElementById('activePaneIndicator');const toggle=document.getElementById('parallelModeToggle');if(toggle)toggle.checked=!!stateBundle.parallelEnabled;if(ind){if(isParallelActive())ind.textContent='Annotating: '+paneLabel(stateBundle.activePane);else if(stateBundle.parallelEnabled)ind.textContent='Parallel mode (widen window for side-by-side)';else ind.textContent='';}
document.querySelectorAll('.parallel-verse-cell').forEach(c=>c.classList.toggle('pane-active',+c.dataset.pane===stateBundle.activePane));document.querySelectorAll('.parallel-pane-head').forEach(h=>h.classList.toggle('parallel-pane-active',+h.dataset.pane===stateBundle.activePane));}
function initParallelMode(){ensureStateBundle();stateBundle.panes[0]=state;stateBundle.generatedRefsByPane[0]=generatedRefs;const toggle=document.getElementById('parallelModeToggle');if(toggle){toggle.onchange=()=>{syncStateBundle();stateBundle.parallelEnabled=!!toggle.checked;render();};}const realign=document.getElementById('realignVersesBtn');if(realign)realign.onclick=()=>{renderParallelEditors();};document.querySelectorAll('.parallel-pane-head').forEach(h=>{h.onclick=()=>{bindActivePane(+h.dataset.pane);renderParallelEditors();};});window.addEventListener('resize',()=>{if(stateBundle.parallelEnabled)render();});const wrap=document.getElementById('parallelCompareWrap');if(wrap&&!wrap.dataset.arcBound){wrap.dataset.arcBound='1';wrap.addEventListener('pointerdown',e=>{if(!arcDraw.active||!isParallelActive())return;const loc=nearestWordLocFromPointParallel(e.clientX,e.clientY);if(!loc){updateArcStatus('Start the arc by pressing on or near a word.');return;}e.preventDefault();arcDraw.isDragging=true;arcDraw.start=cloneLocWithPane(loc);arcDraw.current=cloneLocWithPane(loc);try{wrap.setPointerCapture(e.pointerId);}catch(err){}renderParallelArcOverlays();renderCrossArcOverlay();},true);wrap.addEventListener('pointermove',e=>{if(!arcDraw.active||!arcDraw.isDragging||!isParallelActive())return;e.preventDefault();const loc=nearestWordLocFromPointParallel(e.clientX,e.clientY);if(loc){arcDraw.current=cloneLocWithPane(loc);renderParallelArcOverlays();renderCrossArcOverlay();}},true);wrap.addEventListener('pointerup',e=>{if(!arcDraw.active||!arcDraw.isDragging||!isParallelActive())return;e.preventDefault();const end=nearestWordLocFromPointParallel(e.clientX,e.clientY)||arcDraw.current;const start=arcDraw.start;arcDraw.isDragging=false;arcDraw.start=null;arcDraw.current=null;try{wrap.releasePointerCapture(e.pointerId);}catch(err){}const arc=addArcFromLocsParallel(start,end);if(arc){updateArcStatus(start.pane!==end.pane?'Cross-pane arc added.':'Arc drawn.');toggleDrawArcMode(false);render();}else{renderParallelArcOverlays();renderCrossArcOverlay();}},true);}}
function nearestWordLocFromPointParallel(x,y){const fromPoint=(document.elementsFromPoint?document.elementsFromPoint(x,y):[]).find(el=>el.classList&&el.classList.contains('word'));if(fromPoint)return locFromWordElWithPane(fromPoint);let words=[...document.querySelectorAll('#parallelVerseRows .word')];let best=null,bestDist=Infinity;words.forEach(el=>{const r=el.getBoundingClientRect();const cx=Math.min(Math.max(x,r.left),r.right),cy=Math.min(Math.max(y,r.top),r.bottom);const d=(x-cx)*(x-cx)+(y-cy)*(y-cy);if(d<bestDist){bestDist=d;best=el;}});return bestDist<16000?locFromWordElWithPane(best):null;}
function projectPayloadParallel(){syncStateBundle();return {app:'Hebrew Contour Table App',version:'1.3.9',savedAt:new Date().toISOString(),state:{parallelEnabled:stateBundle.parallelEnabled,activePane:stateBundle.activePane,crossArcs:stateBundle.crossArcs,panes:stateBundle.panes},generatedRefsByPane:stateBundle.generatedRefsByPane,generatedRefs:stateBundle.generatedRefsByPane[stateBundle.activePane]};}
function applyProjectPayloadParallel(payload){let data=(payload&&payload.state)?payload:{state:payload};const normalized=normalizeProjectState(data.state);stateBundle.parallelEnabled=normalized.parallelEnabled;stateBundle.activePane=normalized.activePane;stateBundle.crossArcs=normalized.crossArcs;stateBundle.panes=normalized.panes;stateBundle.generatedRefsByPane=Array.isArray(payload.generatedRefsByPane)?payload.generatedRefsByPane:[Array.isArray(payload.generatedRefs)?payload.generatedRefs:[],[]];bindActivePane(stateBundle.activePane);if(!state.columns)state.columns=[];if(!Array.isArray(state.legend))state.legend=[];if(!Array.isArray(state.inclusios))state.inclusios=[];if(!Array.isArray(state.comments))state.comments=[];if(!Array.isArray(state.arcs))state.arcs=[];state.activeArcId=null;state.activeCommentId=null;state.selected=null;if(document.getElementById('textSource')){const lang=state.language==='greek'?'greek':(state.language==='hebrew-bhsa'?'hebrew-bhsa':'hebrew');document.getElementById('textSource').value=lang;setupBooks();}if(document.getElementById('pasteBox')){const pb=document.getElementById('pasteBox');pb.dir=state.language==='greek'?'ltr':'rtl';pb.classList.remove('heb','greek');pb.classList.add(state.language==='greek'?'greek':'heb');}const refBox=document.getElementById('refBox');if(refBox)refBox.value=state.ref||'';const toggle=document.getElementById('parallelModeToggle');if(toggle)toggle.checked=!!stateBundle.parallelEnabled;}
